{
  "success": false,
  "return_code": 1,
  "stdout": "\ud83c\udf19 Moon Dev Data Loaded: 31066 bars \ud83d\ude80\n\ud83c\udf19 Moon Dev KalmanResonance Initialized \u2728\n\n",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_final/T04_KalmanResonance_BTFinal_v1.py\", line 166, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_final/T04_KalmanResonance_BTFinal_v1.py\", line 86, in next\n    equity = self._broker.getvalue()\nAttributeError: '_Broker' object has no attribute 'getvalue'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_final/T04_KalmanResonance_BTFinal_v1.py` failed. (See above for error)\n",
  "execution_time": 2.419656,
  "timestamp": "2025-10-23T10:01:02.436799"
}