{
  "success": false,
  "return_code": 1,
  "stdout": "\ud83c\udf19 Moon Dev: Data loaded and cleaned \u2728\n\ud83c\udf19 Moon Dev: Indicators initialized \u2728\n\n",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_final/T04_KalmanStochastic_BTFinal_v2.py\", line 155, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_final/T04_KalmanStochastic_BTFinal_v2.py\", line 51, in next\n    if self._i < max_period + 5:\nAttributeError: 'KalmanStochastic' object has no attribute '_i'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_final/T04_KalmanStochastic_BTFinal_v2.py` failed. (See above for error)\n",
  "execution_time": 1.158849,
  "timestamp": "2025-10-23T09:24:28.060120"
}